$(document).ready(function() {
      $("#terms1").click(function(){
        $("#terms1").hide();
      });
      $("#terms1").click(function(){
        $("#show1").show();
      });
      $("#show1").click(function(){
        $("#terms1").show();
      });
      $("#show1").click(function(){
        $("#show1").hide();
      });
});
$(document).ready(function() {
      $("#terms2").click(function(){
        $("#terms2").hide();
      });
      $("#terms2").click(function(){
        $("#show2").show();
      });
      $("#show2").click(function(){
        $("#terms2").show();
      });
      $("#show2").click(function(){
        $("#show2").hide();
      });
});
$(document).ready(function() {
      $("#terms3").click(function(){
        $("#terms3").hide();
      });
      $("#terms3").click(function(){
        $("#show3").show();
      });
      $("#show3").click(function(){
        $("#terms3").show();
      });
      $("#show3").click(function(){
        $("#show3").hide();
      });
});$(document).ready(function() {
      $("#terms4").click(function(){
        $("#terms4").hide();
      });
      $("#terms4").click(function(){
        $("#show4").show();
      });
      $("#show4").click(function(){
        $("#terms4").show();
      });
      $("#show4").click(function(){
        $("#show4").hide();
      });
});$(document).ready(function() {
      $("#terms5").click(function(){
        $("#terms5").hide();
      });
      $("#terms5").click(function(){
        $("#show5").show();
      });
      $("#show5").click(function(){
        $("#terms5").show();
      });
      $("#show5").click(function(){
        $("#show5").hide();
      });
});
